config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :microposts
  resources :animals
  get 'static_pages/home'

  get 'static_pages/about'
  get 'animals' => 'animals#home'
root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'  
  resources :users

end

app/models/animal.rb
class Animal < ActiveRecord::Base
    validates :name,  presence: true, length: { maximum: 50 }
    validates :the_type,  presence: true, length: { maximum: 50 }
    validates :mood, presence: true, length: {maximum: 50}
    validate :validatemood 
    
    
    def validatemood
        if mood != "shy" || mood != "vicious" || mood != "tame"
            errors.add(:mood, "- An animal can only be shy, tame or vicious.");
        end
    end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:name, :the_type, :mood)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_form.html.erb
<%= form_for(@animal) do |f| %>
  <% if @animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% @animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <label>Type</label><br>
    <%= f.text_field :the_type %>
  </div>
  <div class="field">
    <%= f.label :mood %><br>
    <%= f.text_field :mood %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form' %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Animals</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Mood</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |animal| %>
      <tr>
        <td><%= animal.name %></td>
        <td><%= animal.the_type %></td>
        <td><%= animal.mood %></td>
        <td><%= link_to 'Show', animal, class:"btn btn-default" %></td>
        <td><%= link_to 'Edit', edit_animal_path(animal), class:"btn btn-default" %></td>
        <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Animal', new_animal_path, class: "btn btn-primary" %>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form' %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @animal.name %>
</p>

<p>
  <strong>The type:</strong>
  <%= @animal.the_type %>
</p>

<p>
  <strong>Mood:</strong>
  <%= @animal.mood %>
</p>

<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>